In [3]:
import torch
torch.__version__

'2.11.0+cu130'

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [7]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
# Check the number of dimensions of vector
vector.ndim

1

In [10]:
# Check shape of vector
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
# Check number of dimensions
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.1668, 0.7362, 0.6091, 0.6567],
        [0.5800, 0.9996, 0.5753, 0.0357],
        [0.5938, 0.4277, 0.8789, 0.4531]])

In [19]:
random_tensor.dtype

torch.float32

In [20]:
random_tensor = torch.rand(size=(3,224, 224))
random_tensor

tensor([[[0.8449, 0.7241, 0.4001,  ..., 0.5039, 0.8891, 0.5399],
         [0.4602, 0.3077, 0.0014,  ..., 0.8308, 0.7081, 0.5206],
         [0.2052, 0.3760, 0.7754,  ..., 0.4075, 0.3504, 0.6964],
         ...,
         [0.7049, 0.6655, 0.2264,  ..., 0.1608, 0.0197, 0.5513],
         [0.2899, 0.6779, 0.0944,  ..., 0.4131, 0.7314, 0.1806],
         [0.3660, 0.0065, 0.3335,  ..., 0.6370, 0.8009, 0.9388]],

        [[0.5545, 0.6427, 0.7790,  ..., 0.1626, 0.7799, 0.6268],
         [0.2267, 0.0141, 0.0973,  ..., 0.6564, 0.0058, 0.9685],
         [0.8700, 0.2667, 0.5647,  ..., 0.6425, 0.0937, 0.1696],
         ...,
         [0.3408, 0.1178, 0.0364,  ..., 0.5755, 0.8165, 0.2531],
         [0.4156, 0.6506, 0.1047,  ..., 0.6106, 0.4452, 0.6725],
         [0.1139, 0.5060, 0.0638,  ..., 0.9107, 0.4685, 0.3564]],

        [[0.5045, 0.7677, 0.6611,  ..., 0.5013, 0.6985, 0.6390],
         [0.9241, 0.1372, 0.5046,  ..., 0.2957, 0.4479, 0.5981],
         [0.9681, 0.4370, 0.4805,  ..., 0.5339, 0.6883, 0.

In [26]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [27]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [28]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Can also create a tensor of ones similar to another tensor
ten_ones = torch.ones_like(input=zero_to_ten) # will have same shape

# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_ones,ten_zeros

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [36]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [39]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [40]:
# Create a tensor
some_tensor = torch.rand(1,3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[[0.2072, 0.3486, 0.0054, 0.4200],
         [0.4796, 0.0435, 0.5601, 0.4516],
         [0.5981, 0.7206, 0.1296, 0.4066]]])
Shape of tensor: torch.Size([1, 3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [48]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [49]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [50]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [51]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [52]:
# Add 10 to it
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [53]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [54]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

In [55]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
